--[[
    every map area and layouts
]]

-- consts for the in game blocks
EMPTY = 1
ROAD = 2
SIDEWALK = 3
PORTAL = 4
CAMPFIRE = 5

area1 = {
   -- padrão  1 
    {{PORTAL, SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, EMPTY, EMPTY},
    {ROAD, ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, SIDEWALK, ROAD, SIDEWALK, SIDEWALK, EMPTY, EMPTY}},
   -- padrão  2 
    {{PORTAL, EMPTY, SIDEWALK, SIDEWALK, SIDEWALK, EMPTY, EMPTY, EMPTY},
    {ROAD, ROAD, ROAD, ROAD, SIDEWALK, EMPTY, SIDEWALK, EMPTY},
    {EMPTY, SIDEWALK, SIDEWALK, ROAD, EMPTY, EMPTY, EMPTY, SIDEWALK}},
   -- padrão  3 
    {{PORTAL, ROAD, ROAD, SIDEWALK, EMPTY, EMPTY, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, ROAD, ROAD, SIDEWALK, EMPTY, EMPTY, EMPTY},
    {EMPTY, SIDEWALK, SIDEWALK, ROAD, SIDEWALK, EMPTY, SIDEWALK, EMPTY}},
   -- padrão  4 
    {{PORTAL, SIDEWALK, ROAD, ROAD, ROAD, ROAD, ROAD, EMPTY},
    {ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK, SIDEWALK, ROAD, SIDEWALK},
    {EMPTY, SIDEWALK, SIDEWALK, ROAD, ROAD, ROAD, ROAD, SIDEWALK}},
   -- padrão  5 
    {{PORTAL, ROAD, ROAD, SIDEWALK, EMPTY, SIDEWALK, EMPTY, EMPTY},
    {EMPTY, SIDEWALK, ROAD, ROAD, EMPTY, SIDEWALK, SIDEWALK, EMPTY},
    {EMPTY, SIDEWALK, SIDEWALK, ROAD, EMPTY, SIDEWALK, EMPTY, EMPTY}},
   -- padrão  6 
    {{PORTAL, SIDEWALK, ROAD, ROAD, ROAD, ROAD, ROAD, EMPTY},
    {ROAD, ROAD, ROAD, SIDEWALK, EMPTY, SIDEWALK, ROAD, EMPTY},
    {SIDEWALK, SIDEWALK, SIDEWALK, ROAD, ROAD, ROAD, ROAD, SIDEWALK}},
   -- padrão  7 
    {{PORTAL, ROAD, ROAD, ROAD, ROAD, ROAD, SIDEWALK, EMPTY},
    {SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, ROAD, SIDEWALK, EMPTY},
    {EMPTY, SIDEWALK, SIDEWALK, ROAD, ROAD, ROAD, SIDEWALK, EMPTY}},
   -- padrão  8 
    {{PORTAL, ROAD, ROAD, ROAD, ROAD, ROAD, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, EMPTY, SIDEWALK, SIDEWALK, ROAD, SIDEWALK, SIDEWALK},
    {EMPTY, SIDEWALK, EMPTY, ROAD, ROAD, ROAD, SIDEWALK, EMPTY}},
   -- padrão  9 
    {{PORTAL, SIDEWALK, ROAD, ROAD, ROAD, EMPTY, EMPTY, SIDEWALK},
    {ROAD, ROAD, ROAD, SIDEWALK, ROAD, EMPTY, SIDEWALK, EMPTY},
    {SIDEWALK, SIDEWALK, EMPTY, ROAD, ROAD, EMPTY, EMPTY, EMPTY}},
    -- padrão 10 
    {{PORTAL, SIDEWALK, ROAD, ROAD, ROAD, SIDEWALK, EMPTY, EMPTY},
    {ROAD, ROAD, ROAD, EMPTY, ROAD, SIDEWALK, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, SIDEWALK, ROAD, ROAD, SIDEWALK, EMPTY, EMPTY}}
}

area2 = {
   -- padrão  1 
    {{EMPTY, SIDEWALK, ROAD, ROAD, SIDEWALK, EMPTY, SIDEWALK, EMPTY},
    {SIDEWALK, SIDEWALK, ROAD, SIDEWALK, SIDEWALK, EMPTY, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, ROAD, SIDEWALK, EMPTY},
    {ROAD, SIDEWALK, EMPTY, EMPTY, ROAD},
    {ROAD, ROAD, ROAD, ROAD, ROAD}},
   -- padrão  2 
    {{EMPTY, EMPTY, EMPTY, ROAD, EMPTY, EMPTY, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, ROAD, ROAD, SIDEWALK, EMPTY, EMPTY, EMPTY},
    {SIDEWALK, ROAD, ROAD, SIDEWALK, EMPTY},
    {SIDEWALK, ROAD, EMPTY, EMPTY, ROAD},
    {SIDEWALK, ROAD, ROAD, ROAD, ROAD}},
   -- padrão  3 
    {{ROAD, ROAD, ROAD, ROAD, EMPTY, EMPTY, SIDEWALK, EMPTY},
    {ROAD, SIDEWALK, SIDEWALK, SIDEWALK, EMPTY, SIDEWALK, SIDEWALK, EMPTY},
    {ROAD, SIDEWALK, SIDEWALK, SIDEWALK, EMPTY},
    {ROAD, ROAD, ROAD, ROAD, ROAD},
    {SIDEWALK, SIDEWALK, SIDEWALK, EMPTY, EMPTY}},
   -- padrão  4 
    {{EMPTY, EMPTY, EMPTY, ROAD, SIDEWALK, SIDEWALK, EMPTY, EMPTY},
    {SIDEWALK, ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK, EMPTY, EMPTY},
    {SIDEWALK, ROAD, SIDEWALK, SIDEWALK, SIDEWALK},
    {SIDEWALK, ROAD, ROAD, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, ROAD, ROAD, ROAD}},
   -- padrão  5 
    {{EMPTY, SIDEWALK, SIDEWALK, ROAD, EMPTY, EMPTY, EMPTY, EMPTY},
    {EMPTY, SIDEWALK, ROAD, ROAD, SIDEWALK, SIDEWALK, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, ROAD, SIDEWALK, SIDEWALK},
    {SIDEWALK, SIDEWALK, ROAD, EMPTY, ROAD},
    {EMPTY, SIDEWALK, ROAD, ROAD, ROAD}},
   -- padrão  6 
    {{SIDEWALK, SIDEWALK, SIDEWALK, ROAD, SIDEWALK, EMPTY, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, ROAD, ROAD, SIDEWALK, EMPTY, SIDEWALK, SIDEWALK},
    {ROAD, SIDEWALK, SIDEWALK, EMPTY, SIDEWALK},
    {ROAD, ROAD, SIDEWALK, ROAD, ROAD},
    {EMPTY, ROAD, ROAD, ROAD, EMPTY}},
   -- padrão  7 
    {{EMPTY, SIDEWALK, ROAD, ROAD, EMPTY, EMPTY, SIDEWALK, EMPTY},
    {SIDEWALK, SIDEWALK, ROAD, SIDEWALK, EMPTY, EMPTY, SIDEWALK, EMPTY},
    {ROAD, ROAD, ROAD, SIDEWALK, EMPTY},
    {ROAD, SIDEWALK, SIDEWALK, EMPTY, ROAD},
    {ROAD, ROAD, ROAD, ROAD, ROAD}},
   -- padrão  8 
    {{EMPTY, SIDEWALK, SIDEWALK, ROAD, EMPTY, EMPTY, EMPTY, EMPTY},
    {ROAD, ROAD, ROAD, ROAD, EMPTY, EMPTY, EMPTY, EMPTY},
    {ROAD, SIDEWALK, SIDEWALK, SIDEWALK, EMPTY},
    {ROAD, ROAD, ROAD, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, ROAD, ROAD, ROAD}},
   -- padrão  9 
    {{EMPTY, SIDEWALK, SIDEWALK, ROAD, SIDEWALK, EMPTY, SIDEWALK, EMPTY},
    {EMPTY, SIDEWALK, ROAD, ROAD, SIDEWALK, EMPTY, SIDEWALK, SIDEWALK},
    {EMPTY, SIDEWALK, ROAD, SIDEWALK, SIDEWALK},
    {EMPTY, EMPTY, ROAD, ROAD, ROAD},
    {SIDEWALK, EMPTY, EMPTY, SIDEWALK, SIDEWALK}},
    -- padrão 10 
    {{ROAD, ROAD, ROAD, ROAD, EMPTY, SIDEWALK, SIDEWALK, EMPTY},
    {ROAD, SIDEWALK, SIDEWALK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY},
    {ROAD, SIDEWALK, EMPTY, EMPTY, SIDEWALK},
    {ROAD, SIDEWALK, EMPTY, SIDEWALK, ROAD},
    {ROAD, ROAD, ROAD, ROAD, ROAD}}
}

area3 = {
   -- padrão  1 
    {{EMPTY, ROAD, EMPTY},
    {SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, ROAD, SIDEWALK},
    {ROAD, ROAD, ROAD, ROAD, ROAD, SIDEWALK},
    {SIDEWALK, SIDEWALK, EMPTY, EMPTY, SIDEWALK, SIDEWALK}},
   -- padrão  2 
    {{EMPTY, ROAD, SIDEWALK},
    {EMPTY, ROAD, EMPTY},
    {SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, ROAD, SIDEWALK},
    {ROAD, ROAD, ROAD, ROAD, ROAD, SIDEWALK},
    {EMPTY, SIDEWALK, SIDEWALK, EMPTY, EMPTY, SIDEWALK}},
   -- padrão  3 
    {{EMPTY, ROAD, EMPTY},
    {SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, SIDEWALK, EMPTY, ROAD, ROAD, SIDEWALK},
    {ROAD, ROAD, SIDEWALK, ROAD, SIDEWALK, SIDEWALK},
    {EMPTY, ROAD, ROAD, ROAD, SIDEWALK, EMPTY}},
   -- padrão  4 
    {{ROAD, ROAD, SIDEWALK},
    {ROAD, SIDEWALK, SIDEWALK},
    {SIDEWALK, SIDEWALK, SIDEWALK, ROAD, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, SIDEWALK, ROAD, SIDEWALK, EMPTY},
    {SIDEWALK, ROAD, ROAD, ROAD, EMPTY, SIDEWALK}},
   -- padrão  5 
    {{SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, EMPTY},
    {ROAD, ROAD, ROAD, SIDEWALK, ROAD, EMPTY},
    {ROAD, SIDEWALK, ROAD, SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, EMPTY, ROAD, ROAD, ROAD, SIDEWALK}},
   -- padrão  6 
    {{EMPTY, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK},
    {EMPTY, SIDEWALK, SIDEWALK, SIDEWALK, ROAD, EMPTY},
    {ROAD, ROAD, SIDEWALK, ROAD, ROAD, EMPTY},
    {SIDEWALK, ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK}},
   -- padrão  7 
    {{ROAD, ROAD, EMPTY},
    {ROAD, SIDEWALK, SIDEWALK},
    {EMPTY, EMPTY, SIDEWALK, ROAD, ROAD, SIDEWALK},
    {ROAD, ROAD, SIDEWALK, SIDEWALK, ROAD, EMPTY},
    {SIDEWALK, ROAD, ROAD, ROAD, ROAD, SIDEWALK}},
   -- padrão  8 
    {{ROAD, ROAD, EMPTY},
    {ROAD, SIDEWALK, EMPTY},
    {EMPTY, EMPTY, SIDEWALK, ROAD, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK},
    {EMPTY, SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK}},
   -- padrão  9 
    {{EMPTY, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK},
    {EMPTY, EMPTY, SIDEWALK, SIDEWALK, ROAD, SIDEWALK},
    {ROAD, ROAD, ROAD, SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, SIDEWALK, ROAD, ROAD, ROAD, SIDEWALK}},
    -- padrão 10 
    {{SIDEWALK, ROAD, EMPTY},
    {ROAD, ROAD, SIDEWALK},
    {SIDEWALK, SIDEWALK, ROAD, ROAD, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK, EMPTY},
    {EMPTY, SIDEWALK, SIDEWALK, SIDEWALK, EMPTY, EMPTY}}
}

area4 = {
   -- padrão  1 
    {{SIDEWALK, ROAD, ROAD, ROAD, SIDEWALK, EMPTY},
    {SIDEWALK, ROAD, SIDEWALK, ROAD, SIDEWALK, EMPTY},
    {EMPTY, ROAD, SIDEWALK, ROAD, SIDEWALK, SIDEWALK},
    {ROAD, SIDEWALK, SIDEWALK},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, ROAD, ROAD}},
   -- padrão  2 
    {{SIDEWALK, ROAD, ROAD, ROAD, ROAD, EMPTY},
    {SIDEWALK, ROAD, SIDEWALK, SIDEWALK, ROAD, EMPTY},
    {SIDEWALK, ROAD, SIDEWALK, SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, ROAD},
    {EMPTY, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, SIDEWALK},
    {EMPTY, SIDEWALK, EMPTY}},
   -- padrão  3 
    {{EMPTY, ROAD, ROAD, ROAD, SIDEWALK, EMPTY},
    {EMPTY, ROAD, SIDEWALK, ROAD, SIDEWALK, EMPTY},
    {EMPTY, ROAD, SIDEWALK, ROAD, SIDEWALK, EMPTY},
    {ROAD, SIDEWALK, EMPTY},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, ROAD, ROAD},
    {SIDEWALK, SIDEWALK, SIDEWALK}},
   -- padrão  4 
    {{EMPTY, EMPTY, SIDEWALK, SIDEWALK, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK},
    {SIDEWALK, ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK},
    {ROAD, EMPTY, EMPTY},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, ROAD, ROAD}},
   -- padrão  5 
    {{EMPTY, ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK},
    {EMPTY, ROAD, SIDEWALK, ROAD, ROAD, SIDEWALK},
    {EMPTY, ROAD, SIDEWALK, SIDEWALK, ROAD, SIDEWALK},
    {EMPTY, ROAD, EMPTY},
    {EMPTY, ROAD, ROAD},
    {SIDEWALK, SIDEWALK, SIDEWALK},
    {EMPTY, SIDEWALK, SIDEWALK},
    {EMPTY, EMPTY, EMPTY}},
   -- padrão  6 
    {{SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, EMPTY},
    {SIDEWALK, ROAD, ROAD, ROAD, ROAD, SIDEWALK},
    {EMPTY, ROAD, SIDEWALK, SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, ROAD},
    {SIDEWALK, SIDEWALK, EMPTY},
    {EMPTY, EMPTY, EMPTY},
    {EMPTY, EMPTY, EMPTY}},
   -- padrão  7 
    {{SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, SIDEWALK, EMPTY},
    {SIDEWALK, ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK},
    {EMPTY, ROAD, SIDEWALK, ROAD, SIDEWALK, SIDEWALK},
    {ROAD, SIDEWALK, SIDEWALK},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, ROAD, ROAD}},
   -- padrão  8 
    {{SIDEWALK, ROAD, ROAD, ROAD, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK, SIDEWALK, ROAD, SIDEWALK},
    {EMPTY, ROAD, EMPTY, SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, ROAD},
    {SIDEWALK, SIDEWALK, EMPTY},
    {EMPTY, EMPTY, EMPTY},
    {EMPTY, SIDEWALK, SIDEWALK}},
   -- padrão  9 
    {{SIDEWALK, EMPTY, EMPTY, EMPTY, EMPTY, EMPTY},
    {EMPTY, EMPTY, SIDEWALK, SIDEWALK, SIDEWALK, EMPTY},
    {EMPTY, ROAD, ROAD, ROAD, SIDEWALK, SIDEWALK},
    {ROAD, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, ROAD},
    {SIDEWALK, SIDEWALK, SIDEWALK},
    {EMPTY, EMPTY, EMPTY},
    {SIDEWALK, EMPTY, SIDEWALK}},
    -- padrão 10 
    {{SIDEWALK, ROAD, ROAD, ROAD, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK, SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK, ROAD, ROAD, SIDEWALK},
    {ROAD, SIDEWALK, SIDEWALK},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, ROAD, ROAD}},
}

area5 = {
   -- padrão  1 
    {{ROAD, ROAD, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, CAMPFIRE}},
   -- padrão  2 
    {{EMPTY, EMPTY, EMPTY},
    {EMPTY, SIDEWALK, EMPTY},
    {EMPTY, SIDEWALK, SIDEWALK},
    {EMPTY, EMPTY, EMPTY},
    {ROAD, ROAD, ROAD},
    {EMPTY, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, CAMPFIRE}},
   -- padrão  3 
    {{EMPTY, EMPTY, SIDEWALK},
    {EMPTY, EMPTY, EMPTY},
    {SIDEWALK, EMPTY, SIDEWALK},
    {ROAD, ROAD, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {SIDEWALK, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, ROAD},
    {EMPTY, EMPTY, CAMPFIRE}},
   -- padrão  4 
    {{EMPTY, EMPTY, SIDEWALK},
    {EMPTY, SIDEWALK, SIDEWALK},
    {EMPTY, EMPTY, EMPTY},
    {EMPTY, EMPTY, EMPTY},
    {ROAD, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, ROAD},
    {SIDEWALK, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, CAMPFIRE}},
   -- padrão  5 
    {{EMPTY, EMPTY, EMPTY},
    {EMPTY, EMPTY, SIDEWALK},
    {SIDEWALK, EMPTY, SIDEWALK},
    {EMPTY, EMPTY, EMPTY},
    {ROAD, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, ROAD},
    {SIDEWALK, SIDEWALK, CAMPFIRE}},
   -- padrão  6 
    {{EMPTY, EMPTY, EMPTY},
    {EMPTY, EMPTY, EMPTY},
    {EMPTY, EMPTY, EMPTY},
    {EMPTY, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, SIDEWALK},
    {EMPTY, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, CAMPFIRE}},
   -- padrão  7 
    {{EMPTY, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {EMPTY, ROAD, ROAD},
    {EMPTY, ROAD, SIDEWALK},
    {SIDEWALK, ROAD, CAMPFIRE}},
   -- padrão  8 
    {{EMPTY, EMPTY, EMPTY},
    {SIDEWALK, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, ROAD},
    {ROAD, EMPTY, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {SIDEWALK, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, ROAD},
    {EMPTY, EMPTY, CAMPFIRE}},
   -- padrão  9 
    {{EMPTY, EMPTY, EMPTY},
    {SIDEWALK, EMPTY, SIDEWALK},
    {ROAD, ROAD, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {ROAD, SIDEWALK, ROAD},
    {SIDEWALK, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, CAMPFIRE}},
    -- padrão 10 
    {{EMPTY, EMPTY, EMPTY},
    {EMPTY, EMPTY, EMPTY},
    {EMPTY, EMPTY, EMPTY},
    {EMPTY, SIDEWALK, SIDEWALK},
    {ROAD, ROAD, ROAD},
    {SIDEWALK, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, ROAD},
    {EMPTY, SIDEWALK, CAMPFIRE}}
}